### ISSUE TITLE
Add support for Ubuntu 24.04

### ISSUE THREAD

**Issue by maciejgwizdala** [aws/ec2-image-builder-roadmap#100]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Currently there are images for Ubuntu LTS 16.04, 18.04, 20.04 and 22.04, but not 24.04

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I'm trying to upgrade Ubuntu 20.04 to newest LTS image, but it's not available in AWS EC2 Image Builder

**Are you currently working around this issue?**
Stay with old 20.04 image

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by pb8o** [comment]
I noticed Ubuntu 24.04 is available today.

**Comment by austoonz** [comment]
Ubuntu 24.04 is now available as an Image Builder managed image. You can use the latest by specifying either of the following ARNs as the parent image:

* `arn:aws:imagebuilder:us-west-2:aws:image/ubuntu-server-24-lts-arm64/x.x.x`
* `arn:aws:imagebuilder:us-west-2:aws:image/ubuntu-server-24-lts-x86/x.x.x`

**Comment by juancarloespeleta** [comment]
is it available in ap-southeast-1?

**Comment by austoonz** [comment]
This should be available in all regions where EC2 Image Builder and the Ubuntu 24.04 AMI are available.
