### ISSUE TITLE
Documentation for using Ansible with EC2 Image Builder

### ISSUE THREAD

**Issue by girishb-aws** [aws/ec2-image-builder-roadmap#44]
Publish blog describing how to use Ansible with EC2 Image Builder for build instance configuration.

**Comment by yanivpaz** [comment]
Hi
this item is marked as "in production" in the roadmap - https://github.com/aws/ec2-image-builder-roadmap/projects/3

can you kindly guide me where is the document?

**Comment by austoonz** [comment]
You can find the blog post [here](https://aws.amazon.com/blogs/compute/executing-ansible-playbooks-in-your-amazon-ec2-image-builder-pipeline/).
