### ISSUE TITLE
Show live build progress in console

### ISSUE THREAD

**Issue by girishb-aws** [aws/ec2-image-builder-roadmap#53]
Enable CloudWatch Log steaming through the EC2 Image Builder Console.

**Comment by tvb** [comment]
Any ETA on this one @girishb-aws ?

**Comment by girishb-aws** [comment]
https://aws.amazon.com/about-aws/whats-new/2023/03/ec2-image-builder-real-time-build-tracking-build-speeds-image-pipelines/
