### ISSUE TITLE
Support for OVA, VMDK, VHD/VHDX, and raw image import and export to S3

### ISSUE THREAD

**Issue by girishb-aws** [aws/ec2-image-builder-roadmap#56]
Add native support for importing VM Images into EC2 via EC2 Image Builder. These images will be usable as parent images within image recipes. This work will also include console changes to simply the experience.

**Comment by drew3251** [comment]
Just curious, is this live/merged in yet?

**Comment by aaronzielke** [comment]
This feature is available, https://aws.amazon.com/about-aws/whats-new/2021/12/ec2-image-builder-console-custom-image-creation-on-premise-images/

**Comment by drew3251** [comment]
that announcement seems to cover the Import of Images into Imagebuilder from S3. But I do not see any features that allow an export of images to S3, which is what this issue seems to imply.
"Support for OVA, VMDK, VHD/VHDX, and raw image import and EXPORT to S3"

**Comment by austoonz** [comment]
Good point, the announcement didn't speak to exporting.

The [Import and export VM images](https://docs.aws.amazon.com/imagebuilder/latest/userguide/vm-import-export.html) documentation links to the [Create distribution settings for output VM disks](https://docs.aws.amazon.com/imagebuilder/latest/userguide/crud-ami-distribution-settings.html#cli-create-vm-dist-config) content.

The relevant piece on that page is the `s3ExportConfiguration` which handles the export to `VMDK`, `RAW` or `VHD` formats.

API Doc links:
* [CreateDistributionConfiguration](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateDistributionConfiguration.html) API docs
  * [S3ExportConfiguration](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_S3ExportConfiguration.html) detail

**Comment by tomsozolins** [comment]
Is this import from s3 feature supported by aws terraform provider?
