### ISSUE TITLE
Automated Image sharing via Image Pipeline

### ISSUE THREAD

**Issue by girishb-aws** [aws/ec2-image-builder-roadmap#58]
We will add the ability to automatically share newly created AMIs using AWS Organizations.

**Comment by tvb** [comment]
Any ETA on this one @girishb-aws ?

**Comment by bigfoot6uk** [comment]
Any update on this? Desperately needed

**Comment by girishb-aws** [comment]
This feature will be live by end of this month (Nov '21).

**Comment by girishb-aws** [comment]
https://aws.amazon.com/about-aws/whats-new/2021/11/ec2-image-builder-sharing-amis-aws-organization-units/

**Comment by nbmaj1** [comment]
Is this feature available in cfn ??

**Comment by aabodabash-aws** [comment]
Dose Cloudformation support AMI OU sharing or not yet ?

**Comment by buddy-halim** [comment]
I raised the support case as soon as re-invent announcing this features, and console support were updated but there is no ETA for the CFN support (from the case I raised). 

@girishb-aws  any ideas when the CFN support is available?

**Comment by austoonz** [comment]
I cannot recall when it was added, but sharing to AWS Organizations and Organization Units is supported. 

Reference: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-imagebuilder-distributionconfiguration-launchpermissionconfiguration.html
