### ISSUE TITLE
Source DistributionConfiguration inputs 

### ISSUE THREAD

**Issue by taylorbartley** [aws/ec2-image-builder-roadmap#61]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
The ability to source the DistributionConfiguration parameters from an outside source, i.e., S3 file or SSM ParameterStore Parameter.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
My team maintains dozens of accounts. We would like to operationalize golden image distribution. But we create and decomission accounts regularly. Needing to routinely update the DistributionConfiguration when we add or remove accounts will likely result in errors. 

**Are you currently working around this issue?**
We are hardcoding the accounts as a list in CloudFormation, and updating that list as part of our onboarding/decom process.

**Additional context**
https://github.com/aws/ec2-image-builder-roadmap/issues/58 
That issue is related, but so far, working with RAM to fill this need isn't quite appropriate, since RAM itself would likely need to be updated after each new AMI is built. 
Another possible approach would be to allow sharing the AMIs with an Organization or OU in the DistributionConfiguration, similarly to RAM's capabilities. 

**Attachments**
n/a

**Comment by Jjlgo** [comment]
Thank you for your input. The Image Builder team is planning to add support for sharing AMIs with AWS Organizations, as part of roadmap item at https://github.com/aws/ec2-image-builder-roadmap/projects/3#card-55226544.

**Comment by sirsurya** [comment]
+1

**Comment by bigfoot6uk** [comment]
+1

**Comment by bigfoot6uk** [comment]
Any update on this? I was informed by support nearly a year ago that RAM was going to support AMI distribution and image builder could use that as an org distribution mechanism.

**Comment by austoonz** [comment]
Distribution Configurations support sharing to AWS Organizations or Organization Units. Closing.
