### ISSUE TITLE
inspector-test-windows does not support recent Windows Server AMIs

### ISSUE THREAD

**Issue by lvthillo** [aws/ec2-image-builder-roadmap#68]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
EC2 Image Builder Recipes provide some components provided by AWS. One of the components (in the testing phase) is called `inspector-test-windows`. I can only attach this component to a recipe which is using Windows Server 2016 as source. It's not working for Windows Server 2019 or Windows Server 2022. Both component versions (1.0.0 & 1.0.1) aren't working.
In this [AWS labs post](https://aws-labs.net/winlab5-manageinfra/imagebuilder.html) I can see it worked for an older Windows Server 2019 image. It would be nice if this component supports recent Windows Server AMIs.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
`Error: Error message: UnknownError: The value supplied for parameter 'components' is not valid. Component ARN 'arn:aws:imagebuilder:xxx:yyy:component/inspector-test-windows/1.0.1/1' does not support the Parent Image OS Version of Microsoft Windows Server 2019.`

**Are you currently working around this issue?**
How are you currently solving this problem?
No workaround.

**Additional context**
/

**Attachments**
/

**Comment by austoonz** [comment]
This component uses the Amazon Inspector Classic agent and is therefore limited to what can be supported.

Per the [Supported Windows-based operating systems for the Amazon Inspector Classic agent](https://docs.aws.amazon.com/inspector/v1/userguide/inspector_supported_os_regions.html#inspector_supported-win-os) docs, the list (as of this comment) is:

* Windows Server 2019 Base
* Windows Server 2016 Base
* Windows Server 2012 R2
* Windows Server 2012
* Windows Server 2008 R2
