### ISSUE TITLE
Support for Dedicated Hosts

### ISSUE THREAD

**Issue by jimwyatt** [aws/ec2-image-builder-roadmap#70]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to be able to run EC2 Image Builder on Dedicated Hosts with so that I can comply with licensing terms when building BYOL images.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
I need to be able to build BYOL licensed Windows images in a repeatable way and while adhering to licensing terms.  The Import Base Image feature announced at re:Invent is helpful, but not the complete solution. 

**Are you currently working around this issue?**
Hyper-V on bare metal, scripted Windows install, export to VHD, upload to S3, then VM Import

**Additional context**
Anything else we should know?

**Attachments**
If you think you might have additional information that you'd like to include via an attachment, please do - we'll take a look. (Remember to remove any personally-identifiable information.)

**Comment by gustavo-armenta** [comment]
I want to build MacOS images containing infrastructure software (agents, database drivers, browsers, editors)

**Comment by austoonz** [comment]
Image Builder now supports Apple macOS, and accordingly it supports instance launches on Dedicated Hosts.

* [EC2 Image Builder now supports Apple macOS - Whats New](https://aws.amazon.com/about-aws/whats-new/2024/10/ec2-image-builder-apple-macos/)
* [EC2 Image Builder now supports building and testing macOS images - AWS News Blog](https://aws.amazon.com/blogs/aws/ec2-image-builder-now-supports-building-and-testing-macos-images/)
* [CreateInfrastructureConfiguration: placement](https://docs.aws.amazon.com/imagebuilder/latest/APIReference/API_CreateInfrastructureConfiguration.html#imagebuilder-CreateInfrastructureConfiguration-request-placement) now includes host related properties.
