### ISSUE TITLE
Increase Component Limit

### ISSUE THREAD

**Issue by jgard** [aws/ec2-image-builder-roadmap#74]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
I would like to use more than 20 components, which is the limit [as documented](https://docs.aws.amazon.com/imagebuilder/latest/userguide/manage-recipes.html).

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
We're trying to keep our image build environment modular, with small reusable components for several different recipes.  Having a hard limit of 20 forces us to combine components that we'd rather not, and/or keep multiple versions of similar monolithic components.  Combined with this, the limit on component document length almost forces us to download and run external scripts instead of keeping all code in the Component Document, which is better for auditability.

**Are you currently working around this issue?**
Combining components to stay under 20.

**Additional context**

**Attachments**

**Comment by austoonz** [comment]
This is now exposed through Service Quotas.

In Service Quotas, under `EC2 Image Builder`, search for `Components per image recipe`.
