### ISSUE TITLE
Add support for Amazon Linux 2023 to use latest available OS version/Auto-versioning option within Recipe

### ISSUE THREAD

**Issue by rgoltz** [aws/ec2-image-builder-roadmap#78]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Tell us about your request**
Amazon Linux 2022 support is needed for auto-versioning option within the recipe.

**Tell us about the problem you're trying to solve. What are you trying to do, and why is it hard?**
Currently Amazon Linux 2022 is not supported as "Image recipes" of EC2 Image Builder. Normally you select "Select managed images" (Image Builder managed images created by you, shared with you, or provided by AWS.)
The benefit: You can select for each Image the option "Use latest available OS version" (Auto-versioning options). By doing so, the Image Builder Pipeline can pick up the latest AMI, hence you are able automate for future builds.

For Amazon Linux 2 we see a value like "arn:aws:imagebuilder:eu-central-1:aws:image/amazon-linux-2-x86/x.x.x" - "Something" like this sould be available for Amazon Linux 2022 soon, since Amazon Linux 2 will went into EOL.

**Are you currently working around this issue?**
We tried to set the latest Amazon Linux 2022 as "custom AMI ID" - We using EC2 Image Builder to apply the EC2 Image Builder STIG components https://docs.aws.amazon.com/imagebuilder/latest/userguide/toe-stig.html (Security Technical Implementation Guides). We tested this option, but the EC2 Image Builder failed, hence we doesn't know a work around yet.

**Additional context**
In order to make the Amazon Linux 2022 team aware on this issue, we also opened https://github.com/amazonlinux/amazon-linux-2022/issues/155

**Comment by medley56** [comment]
Here's a particular reason this should be expedited: **AL2 is going to lack a compatible NodeJS LTS version starting in September of this year.**

NodeJS LTS 16 is going EOL on September 11, 2023
NodeJS LTS 18 requires glibc >= 2.28
AL2 includes only glibc 2.26

I know Amazon Linux is not EOL until 2025-06-30 but NodeJS LTS compatibility is fast becoming the limiting factor for me. We need to be migrating off of AL2 before NodeJS 16 goes EOL later this year.

**Comment by pb8o** [comment]
AL2023 RC0 was released last month: https://docs.aws.amazon.com/linux/al2023/release-notes/new-packages.html

**Comment by rgoltz** [comment]
AL2023 https://aws.amazon.com/blogs/aws/amazon-linux-2023-a-cloud-optimized-linux-distribution-with-long-term-support/ is now rebranded as AL2023 and released at GA. Having this said, we need support for AL2023 to proceed further based on AWS ImageBuilder.

**Comment by 66string** [comment]
I've hit a road block with Image builder for AWS 2023 Linux in regards to building a component. Opened up a case with AWS support. Let's see what they say.

**Comment by aaronzielke** [comment]
EC2 Image Builder support for Amazon Linux 2023 managed image released (as of end March 2023)

**Comment by mward-LT** [comment]
This perhaps may be worthy of spawning a separate issue, but @66string touched upon what I may also be experiencing: while indeed Amazon Linux 2023 is available as a choice in the Recipes for EC2 Image Builder, it is not a choice for valid OS versions in Build Components.  Amazon Linux 2 is, but Amazon Linux 2023 is not:

![image](https://github.com/aws/ec2-image-builder-roadmap/assets/119040131/54cfd9a5-f811-4eb4-97c5-2be76f958eea)

If you try and select Amazon Linux 2 for the Build Component, and try to use it in a Recipe that is based off of Amazon Linux 2023, it fails with the following error:

```
Failed to create image pipeline
Error message: UnknownError: The value supplied for parameter 'components' is not valid. Component ARN 'arn:aws:imagebuilder:ap-northeast-1:123456789000:component/temp-test-component/1.0.0/1' does not support the Parent Image OS Version of Amazon Linux 2023.
```

**Comment by aaronzielke** [comment]
All, we are investigating the issue and will update the list of available OSes. @66string , I see your AWS Support case and will follow up.

**Comment by mward-LT** [comment]
It looks like Amazon Linux 2023 has been added as an OS choice for Build Components in EC2 Image Builder!  Thanks to the AWS team for the quick turnaround time on this.

![image](https://github.com/aws/ec2-image-builder-roadmap/assets/119040131/c641aca5-4294-4a22-8727-002166743c9c)
